name: Product Name
description: |
    Product dscription
requester:
    - name: Requester name
      email: requester@stone.com.br
leader:
    - name: Leader Name
      email: leader@stone.com.br
team: Team Name
start_date: yyyy/mm/dd
first_deploy_to_production_date: yyyy/mm/dd
applications:
    - https://github.com/stone-payments/app1
    - https://github.com/stone-payments/app2
documents:
    business_requirements: https://stonepayments.atlassian.net/wiki
    project_tracking: https://stonepayments.atlassian.net/wiki
    project_architecture: https://stonepayments.atlassian.net/wiki
    changelog: https://stonepayments.atlassian.net/wiki
    monitoring: https://stonepayments.atlassian.net/wiki
    infrastructure: https://stonepayments.atlassian.net/wiki